[project]
name = "icai-muiaap-operacion-de-modelos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alvaro Figueroa", email = "alvarofigueplaza@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
icai-muiaap-operacion-de-modelos = "icai_muiaap_operacion_de_modelos:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
